
#ifndef MotCle_h
#define MotCle_h

enum Mots{
        ZERO, INT, CHAINE, ID, VOID, EXTERN, RETURN, FOR, WHILE, IF
        , ELSE, CONSTANTE, ACCOLADE_OT, ACCOLADE_FM, CROCH_OT,CROCH_FM, INFEG, DIFF, INF, EGAL, PLUS
        , MOINS, MULTIP, DIV, OU, BARRE, ET, AND, NON, SUPEG, SUP, VIRG, PTVIRG,
        PARENTHOUV, PARENTHFERM, DEBCOMM, FINCOMM, BININF, BINSUP, AFFECT, CH, COMMENT, LIRE, ECRIRE, ERR, ERRCH
        };

#endif /* MOTCLE_h */
